#!/usr/bin/env python3
"""
Rolling temporal LightGCN experiment for the fairness auditor.

Design:
    For evaluation year T:
        1. Build historical data using years < T.
        2. Train LightGCN ONLY on that historical data.
        3. Do NOT create an internal train/validation/test split.
        4. Do NOT run RecBole validation during training.
        5. Save a year-specific checkpoint.
        6. Generate Top-10 recommendations for users who have
           historical activity and an interaction in year T.
        7. Repeat at a two-year cadence.

This is a temporal drift/fairness experiment, not a hyperparameter-
tuning experiment. The actual evaluation-year interactions remain
outside the training data.

The model architecture/batch settings remain aligned with the main
LightGCN configuration:
    n_layers = 1
    train_batch_size = 16384
    learning_rate = 0.001

Temporal training is intentionally reduced to 3 epochs because the
objective is to generate consistent historical snapshots for fairness
analysis rather than optimise recommendation accuracy at every year.

The old 2001 temporal run should NOT be treated as part of the final
comparable series if it was generated by the previous implementation.
"""

from __future__ import annotations

import json
import random
import time
from pathlib import Path

import numpy as np
import pandas as pd
import torch

from recbole.config import Config
from recbole.data import create_dataset
from recbole.data.interaction import Interaction
from recbole.model.general_recommender.lightgcn import LightGCN
from recbole.utils import init_seed


# ============================================================
# PROJECT PATHS
# ============================================================

PROJECT_ROOT = Path(__file__).resolve().parents[2]

INPUT_FILE = (
    PROJECT_ROOT
    / "dataset"
    / "ml-32m-50k"
    / "ml-32m-50k.inter"
)

MAIN_CONFIG_FILE = PROJECT_ROOT / "lightgcn.yaml"

TEMPORAL_DATASET_ROOT = (
    PROJECT_ROOT
    / "dataset"
    / "temporal_lightgcn"
)

CHECKPOINT_DIR = (
    PROJECT_ROOT
    / "saved"
    / "temporal_lightgcn"
)

OUTPUT_DIR = (
    PROJECT_ROOT
    / "outputs"
    / "temporal_recommendations"
)

SUMMARY_DIR = (
    PROJECT_ROOT
    / "outputs"
    / "temporal_lightgcn_summaries"
)

LOG_FILE = (
    PROJECT_ROOT
    / "outputs"
    / "temporal_lightgcn_log.csv"
)


# ============================================================
# TEMPORAL SCOPE
# ============================================================

HISTORICAL_START_YEAR = 1996

# Deliberate two-year cadence.
# The old 2001 run is not used as a final comparable result
# because it came from the previous implementation.
EVALUATION_YEARS = [
    2003,
    2005,
    2007,
    2009,
    2011,
    2013,
    2015,
    2017,
    2019,
    2021,
    2023,
]


# ============================================================
# LIGHTGCN SETTINGS
# ============================================================

N_LAYERS = 1
EMBEDDING_SIZE = 64
REG_WEIGHT = 1e-4

EPOCHS = 3
TRAIN_BATCH_SIZE = 16384
LEARNING_RATE = 0.001

TOP_K = 10

# Recommendation-generation batch size.
# This is separate from the training batch size.
RECOMMENDATION_BATCH_SIZE = 512

MIN_USER_INTERACTIONS = 5
MIN_ITEM_INTERACTIONS = 5

SEED = 42
DEVICE = "cpu"


# ============================================================
# HELPERS
# ============================================================

def set_reproducibility(seed: int = SEED) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    init_seed(seed, reproducibility=True)


def ensure_directories() -> None:
    TEMPORAL_DATASET_ROOT.mkdir(parents=True, exist_ok=True)
    CHECKPOINT_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    SUMMARY_DIR.mkdir(parents=True, exist_ok=True)
    LOG_FILE.parent.mkdir(parents=True, exist_ok=True)


def append_log(row: dict) -> None:
    frame = pd.DataFrame([row])

    if LOG_FILE.exists():
        frame.to_csv(LOG_FILE, mode="a", header=False, index=False)
    else:
        frame.to_csv(LOG_FILE, index=False)


# ============================================================
# LOAD FULL INPUT
# ============================================================

def load_input() -> pd.DataFrame:
    if not INPUT_FILE.exists():
        raise FileNotFoundError(
            f"Input file not found:\n{INPUT_FILE}"
        )

    print("=" * 70)
    print("Loading main 50k interaction dataset")
    print("=" * 70)

    df = pd.read_csv(
        INPUT_FILE,
        sep="\t",
        usecols=[
            "user_id:token",
            "item_id:token",
            "rating:float",
            "timestamp:float",
        ],
    )

    df = df.rename(
        columns={
            "user_id:token": "user_id",
            "item_id:token": "item_id",
            "rating:float": "rating",
            "timestamp:float": "timestamp",
        }
    )

    df["user_id"] = pd.to_numeric(
        df["user_id"], errors="raise"
    ).astype(np.int64)

    df["item_id"] = pd.to_numeric(
        df["item_id"], errors="raise"
    ).astype(np.int64)

    df["rating"] = pd.to_numeric(
        df["rating"], errors="raise"
    ).astype(np.float32)

    df["timestamp"] = pd.to_numeric(
        df["timestamp"], errors="raise"
    ).astype(np.int64)

    df["year"] = pd.to_datetime(
        df["timestamp"],
        unit="s",
        errors="coerce",
    ).dt.year.astype("Int64")

    df = df[df["year"].notna()].copy()
    df["year"] = df["year"].astype(np.int16)

    df = df[
        df["year"] >= HISTORICAL_START_YEAR
    ].copy()

    print(f"Rows loaded: {len(df):,}")
    print(f"Users: {df['user_id'].nunique():,}")
    print(f"Items: {df['item_id'].nunique():,}")
    print(
        f"Years retained: "
        f"{df['year'].min()}-{df['year'].max()}"
    )

    return df


# ============================================================
# BUILD ROLLING DATA
# ============================================================

def build_year_data(
    full_df: pd.DataFrame,
    evaluation_year: int,
) -> tuple[pd.DataFrame, pd.DataFrame]:

    historical_df = full_df[
        full_df["year"] < evaluation_year
    ].copy()

    test_df = full_df[
        full_df["year"] == evaluation_year
    ].copy()

    if historical_df.empty:
        raise ValueError(
            f"No historical data available before "
            f"{evaluation_year}."
        )

    if test_df.empty:
        raise ValueError(
            f"No evaluation data found for "
            f"{evaluation_year}."
        )

    print()
    print("-" * 70)
    print(f"Temporal split: evaluation year {evaluation_year}")
    print("-" * 70)
    print(
        f"Historical period: "
        f"{historical_df['year'].min()}-"
        f"{historical_df['year'].max()}"
    )
    print(
        f"Historical rows: {len(historical_df):,}"
    )
    print(
        f"Historical users: "
        f"{historical_df['user_id'].nunique():,}"
    )
    print(
        f"Historical items: "
        f"{historical_df['item_id'].nunique():,}"
    )
    print(
        f"Evaluation rows: {len(test_df):,}"
    )
    print(
        f"Evaluation users: "
        f"{test_df['user_id'].nunique():,}"
    )

    return historical_df, test_df


# ============================================================
# WRITE RECBole DATASET
# ============================================================

def prepare_recbole_dataset(
    historical_df: pd.DataFrame,
    evaluation_year: int,
) -> tuple[str, Path]:

    dataset_name = (
        f"ml32m_temporal_lightgcn_{evaluation_year}"
    )

    dataset_dir = (
        TEMPORAL_DATASET_ROOT / dataset_name
    )

    dataset_dir.mkdir(
        parents=True,
        exist_ok=True,
    )

    inter_file = (
        dataset_dir
        / f"{dataset_name}.inter"
    )

    # Historical data only.
    output = historical_df[
        [
            "user_id",
            "item_id",
            "rating",
            "timestamp",
        ]
    ].copy()

    output["user_id"] = (
        output["user_id"].astype(str)
    )

    output["item_id"] = (
        output["item_id"].astype(str)
    )

    output["timestamp"] = (
        output["timestamp"].astype(np.int64)
    )

    output = output.rename(
        columns={
            "user_id": "user_id:token",
            "item_id": "item_id:token",
            "rating": "rating:float",
            "timestamp": "timestamp:float",
        }
    )

    if not inter_file.exists():
        print(
            f"Writing historical RecBole file:\n"
            f"{inter_file}"
        )

        output.to_csv(
            inter_file,
            sep="\t",
            index=False,
        )
    else:
        print(
            f"Using existing historical RecBole file:\n"
            f"{inter_file}"
        )

    return dataset_name, dataset_dir


# ============================================================
# CONFIG
# ============================================================

def build_config(dataset_name: str) -> Config:
    if not MAIN_CONFIG_FILE.exists():
        raise FileNotFoundError(
            f"Main LightGCN config not found:\n"
            f"{MAIN_CONFIG_FILE}"
        )

    # Read the existing main LightGCN configuration and override
    # only the settings needed for this temporal experiment.
    config_dict = {
        "dataset": dataset_name,
        "data_path": str(TEMPORAL_DATASET_ROOT),

        "model": "LightGCN",

        "device": DEVICE,

        "n_layers": N_LAYERS,
        "embedding_size": EMBEDDING_SIZE,
        "reg_weight": REG_WEIGHT,

        "epochs": EPOCHS,
        "train_batch_size": TRAIN_BATCH_SIZE,
        "eval_batch_size": TRAIN_BATCH_SIZE,
        "learning_rate": LEARNING_RATE,

        "min_user_inter_num": MIN_USER_INTERACTIONS,
        "min_item_inter_num": MIN_ITEM_INTERACTIONS,

        # Required by the RecBole Dataset/LightGCN configuration.
        # We do NOT call data_preparation() and therefore do NOT
        # use this setting to create a validation/test split.
        "eval_args": {
            "split": {
                "RS": [
                    0.8,
                    0.1,
                    0.1,
                ]
            },
            "group_by": "user",
            "order": "RO",
            "mode": {
                "valid": "uni100",
                "test": "uni100",
            },
        },

        "seed": SEED,
    }

    config = Config(
        model="LightGCN",
        dataset=dataset_name,
        config_file_list=[str(MAIN_CONFIG_FILE)],
        config_dict=config_dict,
    )

    return config


# ============================================================
# MANUAL BPR TRAINING
# ============================================================

def build_positive_sets(
    user_ids: np.ndarray,
    item_ids: np.ndarray,
) -> dict[int, set[int]]:

    positives: dict[int, set[int]] = {}

    for user_id, item_id in zip(
        user_ids,
        item_ids,
    ):
        user_id = int(user_id)
        item_id = int(item_id)

        if user_id not in positives:
            positives[user_id] = set()

        positives[user_id].add(item_id)

    return positives


def sample_negative_items(
    users: np.ndarray,
    item_count: int,
    positive_sets: dict[int, set[int]],
    rng: np.random.Generator,
) -> np.ndarray:

    negatives = rng.integers(
        low=0,
        high=item_count,
        size=len(users),
        dtype=np.int64,
    )

    # Re-sample collisions with each user's historical positives.
    for idx, raw_user in enumerate(users):
        user = int(raw_user)
        positives = positive_sets.get(user, set())

        while int(negatives[idx]) in positives:
            negatives[idx] = rng.integers(
                low=0,
                high=item_count,
            )

    return negatives


def train_temporal_model(
    config: Config,
    evaluation_year: int,
    dataset,
) -> tuple[LightGCN, list[float], float]:

    print()
    print("=" * 70)
    print(
        f"Training LightGCN for {evaluation_year}"
    )
    print("=" * 70)
    print(
        "Training mode: historical data only"
    )
    print(
        "Validation: disabled"
    )
    print(
        f"Epochs: {EPOCHS}"
    )
    print(
        f"Train batch size: {TRAIN_BATCH_SIZE:,}"
    )
    print(
        f"Layers: {N_LAYERS}"
    )

    model = LightGCN(
        config,
        dataset,
    ).to(config["device"])

    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=LEARNING_RATE,
    )

    uid_field = dataset.uid_field
    iid_field = dataset.iid_field

    users = (
        dataset.inter_feat[uid_field]
        .cpu()
        .numpy()
        .astype(np.int64)
    )

    items = (
        dataset.inter_feat[iid_field]
        .cpu()
        .numpy()
        .astype(np.int64)
    )

    positive_sets = build_positive_sets(
        users,
        items,
    )

    rng = np.random.default_rng(SEED)

    n_examples = len(users)
    order = np.arange(n_examples)

    epoch_losses: list[float] = []

    start_time = time.time()

    for epoch in range(EPOCHS):
        epoch_start = time.time()

        rng.shuffle(order)

        total_loss = 0.0
        total_examples = 0

        model.train()

        for start in range(
            0,
            n_examples,
            TRAIN_BATCH_SIZE,
        ):
            batch_idx = order[
                start:start + TRAIN_BATCH_SIZE
            ]

            batch_users = users[batch_idx]
            batch_pos = items[batch_idx]

            batch_neg = sample_negative_items(
                batch_users,
                dataset.item_num,
                positive_sets,
                rng,
            )

            user_tensor = torch.from_numpy(
                batch_users
            ).to(config["device"])

            pos_tensor = torch.from_numpy(
                batch_pos
            ).to(config["device"])

            neg_tensor = torch.from_numpy(
                batch_neg
            ).to(config["device"])

            optimizer.zero_grad()

            user_all, item_all = model.forward()

            user_emb = user_all[user_tensor]
            pos_emb = item_all[pos_tensor]
            neg_emb = item_all[neg_tensor]

            pos_scores = (
                user_emb * pos_emb
            ).sum(dim=1)

            neg_scores = (
                user_emb * neg_emb
            ).sum(dim=1)

            mf_loss = model.mf_loss(
                pos_scores,
                neg_scores,
            )

            u_ego = model.user_embedding(
                user_tensor
            )

            pos_ego = model.item_embedding(
                pos_tensor
            )

            neg_ego = model.item_embedding(
                neg_tensor
            )

            reg_loss = model.reg_loss(
                u_ego,
                pos_ego,
                neg_ego,
                require_pow=config["require_pow"],
            )

            loss = (
                mf_loss
                + REG_WEIGHT * reg_loss
            )

            loss.backward()
            optimizer.step()

            batch_size = len(batch_idx)

            total_loss += (
                float(loss.detach().cpu())
                * batch_size
            )
            total_examples += batch_size

        epoch_loss = (
            total_loss / max(total_examples, 1)
        )

        epoch_losses.append(epoch_loss)

        print(
            f"Epoch {epoch + 1}/{EPOCHS} | "
            f"loss={epoch_loss:.6f} | "
            f"time={(time.time() - epoch_start) / 60:.2f} min"
        )

    training_minutes = (
        time.time() - start_time
    ) / 60.0

    print()
    print(
        f"Training complete for {evaluation_year}"
    )
    print(
        f"Training time: "
        f"{training_minutes:.2f} minutes"
    )

    return (
        model,
        epoch_losses,
        training_minutes,
    )


# ============================================================
# CHECKPOINT
# ============================================================

def save_checkpoint(
    model: LightGCN,
    config: Config,
    evaluation_year: int,
    epoch_losses: list[float],
) -> Path:

    checkpoint_file = (
        CHECKPOINT_DIR
        / f"LightGCN-temporal-{evaluation_year}.pth"
    )

    torch.save(
        {
            "model": "LightGCN",
            "evaluation_year": evaluation_year,
            "state_dict": model.state_dict(),
            "config": dict(
                config.final_config_dict
            ),
            "epoch_losses": epoch_losses,
        },
        checkpoint_file,
    )

    print(
        f"Checkpoint saved:\n"
        f"{checkpoint_file}"
    )

    return checkpoint_file


# ============================================================
# RECOMMENDATIONS
# ============================================================

def generate_recommendations(
    model: LightGCN,
    dataset,
    historical_df: pd.DataFrame,
    test_df: pd.DataFrame,
    evaluation_year: int,
    config: Config,
) -> tuple[pd.DataFrame, int, int]:

    print()
    print("=" * 70)
    print(
        f"Generating Top-{TOP_K} recommendations "
        f"for {evaluation_year}"
    )
    print("=" * 70)

    model.eval()

    user_field = dataset.uid_field
    item_field = dataset.iid_field

    user_token_to_id = (
        dataset.field2token_id[user_field]
    )

    item_id_to_token = (
        dataset.field2id_token[item_field]
    )

    historical_users = set(
        historical_df["user_id"].astype(int)
    )

    evaluation_users = set(
        test_df["user_id"].astype(int)
    )

    overlapping_users = sorted(
        historical_users.intersection(
            evaluation_users
        )
    )

    eligible_users = [
        user_id
        for user_id in overlapping_users
        if str(user_id) in user_token_to_id
    ]

    print(
        f"Evaluation-year users: "
        f"{len(evaluation_users):,}"
    )
    print(
        f"Users with historical history: "
        f"{len(overlapping_users):,}"
    )
    print(
        f"Eligible model users: "
        f"{len(eligible_users):,}"
    )

    # Historical catalogue = everything represented in the
    # historical RecBole dataset after its minimum-frequency filters.
    catalogue_inner = np.arange(
        dataset.item_num,
        dtype=np.int64,
    )

    print(
        f"Historical/model catalogue items: "
        f"{len(catalogue_inner):,}"
    )

    rated_by_user = (
        historical_df
        .groupby("user_id")["item_id"]
        .apply(
            lambda values: set(
                int(x) for x in values
            )
        )
        .to_dict()
    )

    rows: list[dict] = []

    recommendation_start = time.time()

    with torch.no_grad():
        for batch_start in range(
            0,
            len(eligible_users),
            RECOMMENDATION_BATCH_SIZE,
        ):
            user_batch = eligible_users[
                batch_start:
                batch_start + RECOMMENDATION_BATCH_SIZE
            ]

            inner_users = np.array(
                [
                    user_token_to_id[str(user_id)]
                    for user_id in user_batch
                ],
                dtype=np.int64,
            )

            user_tensor = torch.from_numpy(
                inner_users
            ).to(config["device"])

            interaction = Interaction(
                {
                    user_field: user_tensor,
                }
            ).to(config["device"])

            scores = model.full_sort_predict(
                interaction
            )

            scores = scores.reshape(
                len(user_batch),
                dataset.item_num,
            )

            # Mask historical consumption.
            for row_idx, raw_user_id in enumerate(
                user_batch
            ):
                seen_raw = rated_by_user.get(
                    raw_user_id,
                    set(),
                )

                if not seen_raw:
                    continue

                seen_inner = []

                for raw_item_id in seen_raw:
                    token = str(raw_item_id)
                    if token in dataset.field2token_id[item_field]:
                        seen_inner.append(
                            dataset.field2token_id[
                                item_field
                            ][token]
                        )

                if seen_inner:
                    scores[
                        row_idx,
                        torch.tensor(
                            seen_inner,
                            dtype=torch.long,
                            device=scores.device,
                        ),
                    ] = -float("inf")

            k = min(
                TOP_K,
                dataset.item_num,
            )

            top_scores, top_indices = torch.topk(
                scores,
                k=k,
                dim=1,
            )

            top_indices = (
                top_indices
                .cpu()
                .numpy()
            )

            top_scores = (
                top_scores
                .cpu()
                .numpy()
            )

            for row_idx, raw_user_id in enumerate(
                user_batch
            ):
                for rank in range(k):
                    inner_item = int(
                        top_indices[
                            row_idx,
                            rank,
                        ]
                    )

                    raw_item = item_id_to_token[
                        inner_item
                    ]

                    rows.append(
                        {
                            "model": "LightGCN",
                            "year": evaluation_year,
                            "timestamp": (
                                f"{evaluation_year}-12-31"
                            ),
                            "user_id": int(
                                raw_user_id
                            ),
                            "item_id": int(
                                raw_item
                            ),
                            "rank": rank + 1,
                            "score": float(
                                top_scores[
                                    row_idx,
                                    rank,
                                ]
                            ),
                        }
                    )

            processed = min(
                batch_start
                + len(user_batch),
                len(eligible_users),
            )

            print(
                f"Processed users: "
                f"{processed:,}/"
                f"{len(eligible_users):,}"
            )

    output_df = pd.DataFrame(
        rows,
        columns=[
            "model",
            "year",
            "timestamp",
            "user_id",
            "item_id",
            "rank",
            "score",
        ],
    )

    yearly_file = (
        OUTPUT_DIR
        / (
            f"LightGCN-temporal-"
            f"{evaluation_year}-"
            f"top10-recommendations.csv"
        )
    )

    output_df.to_csv(
        yearly_file,
        index=False,
    )

    minutes = (
        time.time() - recommendation_start
    ) / 60.0

    print()
    print(
        f"Recommendation generation complete."
    )
    print(
        f"Rows: {len(output_df):,}"
    )
    print(
        f"Recommendation time: "
        f"{minutes:.2f} minutes"
    )
    print(
        f"Output:\n{yearly_file}"
    )

    return (
        output_df,
        len(eligible_users),
        len(catalogue_inner),
    )


# ============================================================
# RUN ONE YEAR
# ============================================================

def run_one_year(
    full_df: pd.DataFrame,
    evaluation_year: int,
) -> dict:

    checkpoint_file = (
        CHECKPOINT_DIR
        / f"LightGCN-temporal-{evaluation_year}.pth"
    )

    recommendation_file = (
        OUTPUT_DIR
        / (
            f"LightGCN-temporal-"
            f"{evaluation_year}-"
            f"top10-recommendations.csv"
        )
    )

    # Safe resume:
    # If BOTH outputs exist, do not redo the year.
    if (
        checkpoint_file.exists()
        and recommendation_file.exists()
    ):
        print()
        print("=" * 70)
        print(
            f"SKIPPING {evaluation_year}: "
            "checkpoint and recommendations already exist."
        )
        print("=" * 70)

        return {
            "year": evaluation_year,
            "status": "skipped_existing",
            "training_minutes": np.nan,
            "recommendation_minutes": np.nan,
            "eligible_users": np.nan,
            "recommendation_rows": np.nan,
            "last_epoch_loss": np.nan,
            "checkpoint": str(checkpoint_file),
            "recommendations": str(
                recommendation_file
            ),
        }

    year_start = time.time()

    print()
    print("#" * 70)
    print(
        f"STARTING TEMPORAL CHECKPOINT: "
        f"{evaluation_year}"
    )
    print("#" * 70)

    historical_df, test_df = build_year_data(
        full_df,
        evaluation_year,
    )

    dataset_name, _ = (
        prepare_recbole_dataset(
            historical_df,
            evaluation_year,
        )
    )

    config = build_config(
        dataset_name
    )

    print()
    print(
        "Creating filtered RecBole dataset "
        "for historical training..."
    )

    # create_dataset() is used only to construct the filtered graph
    # dataset. We deliberately DO NOT call data_preparation().
    dataset = create_dataset(config)

    print(dataset)

    model, epoch_losses, training_minutes = (
        train_temporal_model(
            config,
            evaluation_year,
            dataset,
        )
    )

    save_checkpoint(
        model,
        config,
        evaluation_year,
        epoch_losses,
    )

    recommendation_start = time.time()

    output_df, eligible_users, catalogue_size = (
        generate_recommendations(
            model,
            dataset,
            historical_df,
            test_df,
            evaluation_year,
            config,
        )
    )

    recommendation_minutes = (
        time.time() - recommendation_start
    ) / 60.0

    total_minutes = (
        time.time() - year_start
    ) / 60.0

    summary = {
        "year": evaluation_year,
        "status": "completed",
        "historical_start": int(
            historical_df["year"].min()
        ),
        "historical_end": int(
            historical_df["year"].max()
        ),
        "historical_rows": int(
            len(historical_df)
        ),
        "evaluation_rows": int(
            len(test_df)
        ),
        "historical_users": int(
            historical_df["user_id"].nunique()
        ),
        "evaluation_users": int(
            test_df["user_id"].nunique()
        ),
        "model_users": int(
            dataset.user_num
        ),
        "model_items": int(
            dataset.item_num
        ),
        "eligible_users": int(
            eligible_users
        ),
        "recommendation_rows": int(
            len(output_df)
        ),
        "epochs": int(EPOCHS),
        "train_batch_size": int(
            TRAIN_BATCH_SIZE
        ),
        "n_layers": int(N_LAYERS),
        "learning_rate": float(
            LEARNING_RATE
        ),
        "last_epoch_loss": float(
            epoch_losses[-1]
        ) if epoch_losses else np.nan,
        "training_minutes": float(
            training_minutes
        ),
        "recommendation_minutes": float(
            recommendation_minutes
        ),
        "total_minutes": float(
            total_minutes
        ),
        "checkpoint": str(
            checkpoint_file
        ),
        "recommendations": str(
            OUTPUT_DIR
            / (
                f"LightGCN-temporal-"
                f"{evaluation_year}-"
                f"top10-recommendations.csv"
            )
        ),
    }

    summary_file = (
        SUMMARY_DIR
        / f"LightGCN-temporal-{evaluation_year}-summary.json"
    )

    with open(
        summary_file,
        "w",
        encoding="utf-8",
    ) as handle:
        json.dump(
            summary,
            handle,
            indent=2,
        )

    append_log(summary)

    print()
    print("#" * 70)
    print(
        f"CHECKPOINT {evaluation_year} COMPLETE"
    )
    print(
        f"Training time: "
        f"{training_minutes:.2f} minutes"
    )
    print(
        f"Recommendation time: "
        f"{recommendation_minutes:.2f} minutes"
    )
    print(
        f"Total time: "
        f"{total_minutes:.2f} minutes"
    )
    print("#" * 70)

    return summary


# ============================================================
# MAIN
# ============================================================

def main() -> None:
    ensure_directories()
    set_reproducibility()

    print()
    print("=" * 70)
    print("ROLLING TEMPORAL LIGHTGCN — REVISED")
    print("=" * 70)
    print(
        f"Evaluation years: {EVALUATION_YEARS}"
    )
    print(
        f"Historical start: "
        f"{HISTORICAL_START_YEAR}"
    )
    print(
        f"Epochs per checkpoint: {EPOCHS}"
    )
    print(
        f"Training batch size: "
        f"{TRAIN_BATCH_SIZE:,}"
    )
    print(
        f"LightGCN layers: {N_LAYERS}"
    )
    print(
        "Internal validation: DISABLED"
    )
    print(
        "Temporal cadence: every 2 years"
    )
    print("=" * 70)

    full_df = load_input()

    summaries = []

    for evaluation_year in EVALUATION_YEARS:
        try:
            result = run_one_year(
                full_df,
                evaluation_year,
            )
            summaries.append(result)

        except KeyboardInterrupt:
            print()
            print(
                "Interrupted by user. "
                "Completed years remain saved."
            )
            raise

        except Exception as exc:
            print()
            print(
                f"ERROR in year {evaluation_year}: "
                f"{exc}"
            )

            error_row = {
                "year": evaluation_year,
                "status": "error",
                "error": str(exc),
            }

            summaries.append(error_row)
            append_log(error_row)

    final_summary_file = (
        SUMMARY_DIR
        / "LightGCN-temporal-run-summary.json"
    )

    with open(
        final_summary_file,
        "w",
        encoding="utf-8",
    ) as handle:
        json.dump(
            summaries,
            handle,
            indent=2,
            default=str,
        )

    print()
    print("=" * 70)
    print(
        "ROLLING TEMPORAL LIGHTGCN COMPLETE"
    )
    print("=" * 70)
    print(
        f"Summary:\n{final_summary_file}"
    )


if __name__ == "__main__":
    main()
